"""
Django settings for ebk_online_registration project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

##  Specify Email config ##

## specify Backend (default backend is SMTP); 'django.core.mail.backends.console.EmailBackend' is development backend for console output
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

## specify mail host (default is localhost)
# EMAIL_HOST = ''

## specifiy mail host port (default is 25)
#EMAIL_PORT = ''

## specify mail host user (default is '')
#EMAIL_HOST_USER = ''

## specify mail host user password (default is '')
#EMAIL_HOST_PASSWORD = ''

## specify if TLS should be used (default is False; only set TLS or SSL to true)
#EMAIL_USE_TLS = 'True'

## specify if SSL should be used (default is False)
#EMAIL_USE_SSL = 'True'

## specify timeout time (default is None)
#EMAIL_TIMEOUT = ''

## specify SSL keyfile (default is None)
#EMAIL_SSL_KEYFILE = ''

## specify SSL certfile (default is None)
#EMAIL_SSL_CERTFILE 

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=+v)38%sihkn)g(wdnv1y1m@+@*@(ldrnbiw$v$e%qgdedw^3%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ebk_online_registration.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ebk_online_registration.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# MySQL/MariaDB for productive setting
#DATABASES = {
#	'default': {
#		'ENGINE': 'django.db.backends.mysql',
#		'NAME': 'map',
#		'USER': 'username',
#		'PASSWORD': 'password',
#		'HOST': 'localhost',
#		'PORT':'',
#	}
#}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
