# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberregistration',
            name='entrydate',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='memberregistration',
            name='submitted_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
