# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sirname', models.CharField(max_length=250)),
                ('sex', models.CharField(choices=[('male', 'Mann'), ('female', 'Frau'), ('other', 'other')], max_length=25)),
                ('street', models.CharField(max_length=250)),
                ('streetnumber', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=25)),
                ('birthdate', models.DateField()),
                ('entrydate', models.DateField()),
                ('fee', models.FloatField()),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(max_length=11)),
                ('bankname', models.CharField(max_length=250)),
                ('memberstatus', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
