# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20170129_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='privacy_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='rules_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='sepa_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='submitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
