# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20170129_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fee',
            field=models.FloatField(choices=[('24.0', 'normal'), ('18.0', 'reduced'), ('5.0', 'sustain_min'), ('0.0', 'other'), ('0.0', 'sustain_other')]),
        ),
    ]
