# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20170204_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rules_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='sepa_agree',
            field=models.BooleanField(default=False),
        ),
    ]
