# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20170205_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fee',
            field=models.FloatField(choices=[('normal', 24), ('reduced', 18), ('sustain_min', 5), ('other', 0), ('sustain_other', 0)]),
        ),
    ]
