# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20170212_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bic',
            field=localflavor.generic.models.BICField(max_length=11),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='iban',
            field=localflavor.generic.models.IBANField(include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), max_length=34, use_nordea_extensions=False),
        ),
    ]
