# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20170214_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='sirname',
            new_name='surname',
        ),
    ]
