# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_auto_20170215_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthdate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberstatus',
            field=models.CharField(choices=[('member', 'Mitglied'), ('sustaining_member', 'Fördermitglied'), ('junior_member', 'Juniormitglied')], max_length=25),
        ),
    ]
