# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-16 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20170817_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberstatus',
            field=models.CharField(choices=[(b'member', b'Mitglied'), (b'sustaining_member', b'F\xc3\xb6rdermitglied'), (b'junior_member', b'Juniormitglied')], max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'approved', b'approved'), (b'rejected', b'rejected'), (b'exported', b'exported')], max_length=25),
        ),
    ]
