# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-08 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20180316_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'approved', b'approved'), (b'rejected', b'rejected'), (b'exported', b'exported'), (b'mail_sent', b'mail_sent')], max_length=25),
        ),
    ]
