# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20190608_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membernumber',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
